import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useTranslation } from "../i18n/useTranslation";
import "./ConsentScreen.css";
export default function ConsentScreen({ onConsent }) {
    const { t } = useTranslation();
    const [agreed, setAgreed] = useState(false);
    const handleConsent = () => {
        localStorage.setItem("privacy_consent", "true");
        onConsent();
    };
    return (_jsx("div", { className: "consent-root", children: _jsxs("div", { className: "consent-card", children: [_jsx("h1", { className: "consent-title", children: t("consent.title") }), _jsx("p", { className: "consent-subtitle", children: t("consent.subtitle") }), _jsxs("div", { className: "consent-section", children: [_jsx("div", { className: "consent-section-title", children: t("consent.section_title") }), _jsxs("div", { className: "consent-items", children: [_jsxs("div", { className: "consent-item", children: [_jsx("span", { className: "consent-item-icon", children: "\uD83D\uDDA5\uFE0F" }), _jsxs("div", { className: "consent-item-text", children: [_jsx("div", { className: "consent-item-label", children: t("consent.item_capture_label") }), _jsx("div", { className: "consent-item-desc", children: t("consent.item_capture_desc") })] })] }), _jsxs("div", { className: "consent-item", children: [_jsx("span", { className: "consent-item-icon", children: "\uD83C\uDF10" }), _jsxs("div", { className: "consent-item-text", children: [_jsx("div", { className: "consent-item-label", children: t("consent.item_transfer_label") }), _jsx("div", { className: "consent-item-desc", children: t("consent.item_transfer_desc") })] })] }), _jsxs("div", { className: "consent-item", children: [_jsx("span", { className: "consent-item-icon", children: "\uD83D\uDDD1\uFE0F" }), _jsxs("div", { className: "consent-item-text", children: [_jsx("div", { className: "consent-item-label", children: t("consent.item_storage_label") }), _jsx("div", { className: "consent-item-desc", children: t("consent.item_storage_desc") })] })] }), _jsxs("div", { className: "consent-item", children: [_jsx("span", { className: "consent-item-icon", children: "\uD83D\uDCBE" }), _jsxs("div", { className: "consent-item-text", children: [_jsx("div", { className: "consent-item-label", children: t("consent.item_training_label") }), _jsx("div", { className: "consent-item-desc", children: t("consent.item_training_desc") })] })] })] })] }), _jsxs("div", { className: "consent-safe", children: [_jsx("span", { className: "consent-safe-icon", children: "\uD83D\uDEE1\uFE0F" }), _jsx("span", { children: t("consent.safety") })] }), _jsxs("label", { className: "consent-checkbox-row", children: [_jsx("input", { type: "checkbox", className: "consent-checkbox", checked: agreed, onChange: (e) => setAgreed(e.target.checked) }), _jsx("span", { className: "consent-checkbox-label", children: t("consent.checkbox_label") })] }), _jsx("button", { type: "button", className: "btn-consent", disabled: !agreed, onClick: handleConsent, children: t("consent.button") })] }) }));
}
